# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

# Connet to Docker:
# export DOCKER_HOST=tcp://192.168.66.4:2375

Vagrant.configure('2') do |config|
  # Vagrant-hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true

  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'docker.local'

  config.vm.network 'private_network', ip: '192.168.66.4'
  config.vm.network 'forwarded_port', guest: 2375, host: 2375, id: 'dockerd'
  config.vm.network 'forwarded_port', guest: 80, host: 80, id: 'http'
  config.vm.network 'forwarded_port', guest: 2000, host: 2000, id: 'xray', protocol: "udp"
  config.vm.network 'forwarded_port', guest: 6379, host: 6379, id: 'redis'
  config.vm.network 'forwarded_port', guest: 9527, host: 9527, id: 'httpbin'

  config.vm.provision "docker"
  config.vm.provision 'shell', path: 'provision.sh'
end
