version: "3"

services:
  vault-agent:
    image: "vault:latest"
    volumes:
      - ./cert-generator/certs:/vault/certs
      - ./client:/vault/config
    ports:
      - 8100:8100
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
    command: sh -c "vault agent -config=/vault/config/config.hcl -address=$VAULT_ADDR"
    depends_on:
      - consul-template

  consul-template:
    build:
      context: .
      dockerfile: cert-generator.Dockerfile
    volumes:
      - ./cert-generator:/consul-template/config
    environment:
      CLIENT_NAME: ${CLIENT_NAME}
      PKI_INT_VAULT_ADDR: ${PKI_INT_VAULT_ADDR}
      PKI_INT_VAULT_TOKEN: ${PKI_INT_VAULT_TOKEN}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24
