version: "3"

volumes:
  consul-data:
  client-data:

services:
  vault-agent:
    image: "vault:latest"
    build:
      context: .
      dockerfile: agent.Dockerfile
    volumes:
      - client-data:/vault
      - ./cert-generator/certs:/vault/certs
      - ./client:/vault/config
    ports:
      - 8100:8100
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
    depends_on:
      - consul-template

  redis:
    image: "redis:alpine"
    volumes:
      - ./cert-generator/certs/redis:/redis/certs
      - ./redis:/redis/config
    environment:
      WITH_REDIS: ${WITH_REDIS}
    command: sh -c "[ \"$WITH_REDIS\" = 'true' ] && redis-server /redis/config/redis.conf || echo 'You have disabling Redis!'"
    depends_on:
      - consul-template

  consul-template:
    build:
      context: .
      dockerfile: cert-generator.Dockerfile
    volumes:
      - consul-data:/consul-template
      - ./cert-generator:/consul-template/config
    environment:
      CLIENT_NAME: ${CLIENT_NAME}
      PKI_INT_VAULT_ADDR: ${PKI_INT_VAULT_ADDR}
      PKI_INT_VAULT_TOKEN: ${PKI_INT_VAULT_TOKEN}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24
